apiVersion: v2
name: agentflow-pro
description: A Helm chart for AgentFlow Pro Deployment
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: mongodb
    version: 13.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.enabled
  - name: redis
    version: 18.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
